### ISSUE TITLE
[New Feature]: Home button

### ISSUE THREAD

**Issue by Harsh-KumarJha** [GameSphere-MultiPlayer/Spaceship-escort#14]
### 🎮 feature Request

The Go to **home** button should be on the game panel to take user back to home page
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/121922047/c380b2c3-a15b-421c-88b5-9475bc39cde2)

### Point down the features

1. Users can easily navigate to home using this button .
2. Also can add the pause button on the opposite end to home button .
3. Further we can also add navigation through home buttons when we add different features or modes that can be accessed via home page or any other page.
This will enhance the user experience

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Unknownmaster0** [comment]
Hii, PA may I help in adding the Home button feature.

**Comment by Unknownmaster0** [comment]
Assign this task to me

**Comment by Durgesh4993** [comment]
@Unknownmaster0 Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
