### ISSUE TITLE
[Bug]:  Buttons are not accessable

### ISSUE THREAD

**Issue by sivaprasath2004** [GameSphere-MultiPlayer/Spaceship-escort#15]
### Give a brief about the bug ✍️

- In the `pause` and `Help` that are not pointing only `cursor` can be showed.
- in this bug can be not `clickable` performance user identify.
- please assign me to improve the feature.

### What is the expected behavior? 🤔

- if we will hover the buttons are `pointing` but that is not be abled.

### Provide step by step information reproduce the bug 📄

[Screencast from 2024-05-12 08-46-40.webm](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/121082414/92626239-8518-468b-8830-ae52cb02a136)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@sivaprasath2004 Please raise any other issue, because someone is already working on it
