### ISSUE TITLE
[Bug]: Missing favicon

### ISSUE THREAD

**Issue by nagamukesh** [GameSphere-MultiPlayer/Spaceship-escort#19]
### Give a brief about the bug ✍️

Description
There is no favicon for the web app 
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/112798996/5376be6f-046e-4fdd-aed8-5dfc7235c753)

### What is the expected behavior? 🤔

Description
I can add a relevant favicon to this website

### Provide step by step information reproduce the bug 📄

Description
I can add a favicon by saving an icon and then linking it in HTML
please assign me this issue
I will solve it real quick

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by drashtigit** [comment]
@Durgesh4993  Can you please assign me this issue. will be happy to do it.

**Comment by Missdivyaa** [comment]
@Durgesh4993 I can add a favicon to the website,
please assign me this issue

**Comment by solanki505** [comment]
I would like to work on this issue, please assign me this under gssoc'24

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
