### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [GameSphere-MultiPlayer/Spaceship-escort#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by KUMUD-TECH** [comment]
Is this issue resolved because codes of conduct are already done maybe.

**Comment by Rohit153672** [comment]
hey i want to solve this issue please assign it to me

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Also I have contributed to roadmap.sh's documentation which is one of the most starred repository on GitHub!!

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/98798977/7ad5146a-a84d-4268-97cd-2be4a3e4f62a)

**Comment by Durgesh4993** [comment]
We are already have code of conduct file

**Comment by Durgesh4993** [comment]
@nsk6704 @KUMUD-TECH @Rohit153672 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
