### ISSUE TITLE
[Documentation Bug]: Missing Code of conduct file

### ISSUE THREAD

**Issue by Parimalasri13** [GameSphere-MultiPlayer/Spaceship-escort#26]
### Describe the bug ✍️

file missing

### Provide step by step information reproduce the bug 📄

Descriptionthis file helps to know the rules  and things to be followed 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Parimalasri13** [comment]
@Durgesh4993 can you please assign this to me  I am a GSSOC24 contributor

**Comment by aasthakourav20** [comment]
Hey @GameSphere-Multiplayer ,
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md
 I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by Durgesh4993** [comment]
We already have code of conduct file in GitHub folder
