### ISSUE TITLE
Control Panel UI

### ISSUE THREAD

**Issue by Rohitha-pudu** [GameSphere-MultiPlayer/Spaceship-escort#27]
### the controls are tiny and UX is effected
I wank to work on this issue please assign this to me
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/116823590/3dbc7ca2-e5e8-4903-9ed9-2137a278f194)

**Comment by Durgesh4993** [comment]
Thai task is already assigned to someone else, please raise any other issues I'll assign you
