### ISSUE TITLE
[Documentation Bug]: missing Code of Conduct file #26

### ISSUE THREAD

**Issue by pruthviraj-desale** [GameSphere-MultiPlayer/Spaceship-escort#35]
### Describe the bug ✍️

The code of conduct file is missing, and i would like to add it to github repo #26

### Provide step by step information reproduce the bug 📄

Description
the github repo is missing a code of conduct.md file, it is a help to others as it declares what are the points to be kept in mind while contributing to the project

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
We already have code of conduct file in GitHub folder, kindly check
