### ISSUE TITLE
Add A Login Page

### ISSUE THREAD

**Issue by KrishnaSaxena108** [GameSphere-MultiPlayer/Spaceship-escort#42]
### 🎮 feature Request

Hi i want to add a login page that helps to make this website more versatile 

### Point down the features

Login Page will take Email and Password as input and if no input is provided then it will not move to next page also an toast notification will be shown when no input is entered.
Please assign this issue to me under GSSoC'24.

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
