### ISSUE TITLE
[New Feature]: End game feature

### ISSUE THREAD

**Issue by sharmi4590** [GameSphere-MultiPlayer/Spaceship-escort#43]
### 🎮 feature Request

This game only has a pause button but do not have a restart button or end button.

### Point down the features

By adding this the user will not get confused if he wants to come again to the new page or restart a game.I will make sure to add that in the game .

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
