### ISSUE TITLE
Title is not present

### ISSUE THREAD

**Issue by Ajita369** [GameSphere-MultiPlayer/Spaceship-escort#49]
### Give a brief about the bug ✍️

The title of the game is not present which we see near the favicon.
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/162597493/989d00d2-3b54-4527-b67b-6a745d6070db)  
Here is the screenshot for the same . favicon is also not there but I have seen that somebody already raised that issue.

### What is the expected behavior? 🤔

The title is should be there.

### Provide step by step information reproduce the bug 📄

I will like to work on this issue so please assign this issue to me under GSSOC'24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/98798977/0007afca-8d77-4447-8e21-297ae00df241)

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
