### ISSUE TITLE
[Bug]:  selected and placed missiles are not visible . 

### ISSUE THREAD

**Issue by Sushanth-Hebri** [GameSphere-MultiPlayer/Spaceship-escort#8]
### Give a brief about the bug ✍️

Description:
What user is selected is only highlighted in control menu , but when it is placed its not visible except last one.
lets handle image properly.

### What is the expected behavior? 🤔

Description :
images should be seen

### Provide step by step information reproduce the bug 📄

Description:
please assign this issue to me so that i can contribute to enhance game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
